import "./globals.css";
import localFont from "next/font/local";
const font = localFont({
  src: [
    {
      path: "../public/font/bahij_roya_irfont.ttf",
      weight: "200",
      style: "normal",
    }
  ]
})

export const metadata = {
  title: "سجاد حسنی کاخ | طراح و برنامه نویس وب",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={font.className}>
        {children}
      </body>
    </html>
  );
}
